### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Kc2fresh** [GoddessChysomme/FOMODPSO#1]
Dataset used for the research FOMODPSO
[G1-G14.pdf](https://github.com/GoddessChysomme/FOMODPSO/files/13933461/G1-G14.pdf)

**Comment by GoddessChysomme** [comment]
Four widely applied evaluation metrics are employed to carry out a thorough objective assessment, including entropy (ENT), mutual information (MI), Q_abf, and structural similarity index (SSIM). ENT evaluates the overall details in the fused image. MI measures the mutual information that can be found between the source and fused images. Q_abf measures the quality of edge details transferred from source images to their respective fused images. SSIM gives the resemblance in structure, brightness and contrast between source and fused images. As can be seen in Table 3, the objective assessment performance of our multimodal medical image fusion method, and other state-of-the-art comparative MMIF methods, were conducted, where the highest score values are indicated boldfaced in each column, which shows the best results. From the Table, it can be seen that our proposed method gives the superior performance results.

**Comment by GoddessChysomme** [comment]
Four widely applied evaluation metrics are employed to carry out a thorough objective assessment, including entropy (ENT), mutual information (MI), Q_abf, and structural similarity index (SSIM). ENT evaluates the overall details in the fused image. MI measures the mutual information that can be found between the source and fused images. Q_abf measures the quality of edge details transferred from source images to their respective fused images. SSIM gives the resemblance in structure, brightness and contrast between source and fused images. As can be seen in Table 3, the objective assessment performance of our multimodal medical image fusion method, and other state-of-the-art comparative MMIF methods, were conducted, where the highest score values are indicated boldfaced in each column, which shows the best results. From the Table, it can be seen that our proposed method gives the superior performance results.

**Comment by GoddessChysomme** [comment]
marked as closed
